server:
    port: 8050
    max-http-header-size: 64kb
    servlet:
        context-path: /api/v1/permission-checker
spring:
    profiles:
        active: ${SPRING_ACTIVE_PROFILE:dev}
    application:
        name: ofx-permission-checker  
    security:
        oauth2:
            resourceserver:
                jwt:
                    issuer-uri: http://localhost:9091/realms/luifj-ofx-auth
    datasource:
        url: jdbc:postgresql://${conf.db.host}:${conf.db.port}/${conf.db.database}
        username: ${conf.db.user}
        password: ${conf.db.pass}
        driver-class-name: org.postgresql.Driver
    jpa:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        hibernate:
            ddl-auto: none
    flyway:
        user: ${conf.db.user}
        password: ${conf.db.pass}
        schemas: public
        url: jdbc:postgresql://${conf.db.host}:${conf.db.port}/${conf.db.database}
    rabbitmq:
      host: ${conf.rabbit.host}
      port: ${conf.rabbit.port}
      username: ${conf.rabbit.user}
      password: ${conf.rabbit.pass}

eureka:
  client:
    service-url:
      defaultZone : http://localhost:8761/eureka/                   
keycloak:
    realm: luifj-ofx-auth
    adminClientId: luisfj-ofx-backend-admin
    adminClientSecret: Oczq2jdykpvBZIZ3QICb31jlJjaTwZiH
    urls:
        auth: http://localhost:9091

#logging:
#  level:
#    root: DEBUG
#    org.springframework.web: DEBUG
#    dev.luisjohann.ofxpermissionchecker: DEBUG
#    org.springframework.security: DEBUG
#    org.springframework.security.oauth2: DEBUG
#    org.springframework.security.web.authentication: DEBUG
#    org.springframework.security.oauth2.client: DEBUG
#    org.springframework.security.oauth2.jwt: DEBUG
#    org.springframework.security.oauth2.server.resource: DEBUG
#    org.keycloak: DEBUG
#    org.keycloak.adapters: DEBUG
#    org.keycloak.authentication: DEBUG
#    org.keycloak.events: DEBUG
#    org.apache.http: DEBUG
#    org.springframework.web.reactive.DispatcherHandler: DEBUG
#    org.springframework.web.reactive.function.client: DEBUG
#    org.springframework.web.reactive.function.server: DEBUG
#    org.springframework.web.filter.reactive: DEBUG
#
#org:
#  slf4j:
#    simpleLogger:
#      defaultLogLevel: DEBUG

queue:
  name:
    user-change: change.user.queue
    ue-change: change.ue.queue
  routing-key:
    user-change: changes.user
    ue-change: changes.ue
exchange:
  name: ofx.app