conf:
    db:
        host: localhost
        port: 5777
        database: ofxdb
        user: postgres
        pass: postgres
    rabbit:
        host: localhost
        port: 5672
        user: admin
        pass: admin