server:
    port: 8050
    servlet:
        context-path: /api/v1/permission-checker
spring:
    profiles:
        active: ${SPRING_ACTIVE_PROFILE:dev}
    application:
        name: ofx-permission-checker