server:
    port: 8050
    servlet:
        context-path: /api/v1/permission-checker
spring:
    profiles:
        default: dev
        active: ${SPRING_ACTIVE_PROFILE:default}
    application:
        name: ofx-permission-checker